export const LOAD_PROJECTS = 'LOAD_PROJECTS';
export const SELECT_TASK = 'SELECT_TASK';
export const SELECT_PROJECT = 'SELECT_PROJECT';
export const DESELECT_PROJECT = 'DESELECT_PROJECT';
export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS';
export const ADD_PROJECT = 'ADD_PROJECT';
